# Generated by Django 4.2.24 on 2025-09-05 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสห้อง')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อห้อง')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='ความจุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'ห้องเรียน',
                'verbose_name_plural': 'ห้องเรียน',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ/วิชา')),
                ('start', models.DateTimeField(verbose_name='เริ่ม')),
                ('end', models.DateTimeField(verbose_name='สิ้นสุด')),
                ('status', models.CharField(choices=[('active', 'ใช้งาน'), ('cancelled', 'ยกเลิก')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การจอง',
                'verbose_name_plural': 'การจอง',
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['room', 'start', 'end', 'status'], name='rooms_booki_room_id_55f3d2_idx')],
            },
        ),
    ]
